### ISSUE TITLE
Navigation bar is pretty broken

### ISSUE THREAD

**Issue by urmilshroff** [urmilshroff/mozilla_materialized#9]
Top navigation bar (of Bootstrap MD) (`.navbar.navbar-expand-lg.navbar-light bg-light`) is broken in a couple of ways. Small image doesn't display correctly, no material animation on click of an item, and upon resizing to mobile layout, clicking the hamburger menu lines doesn't do anything.

**Comment by prince1998** [comment]
The issue was solved! :)
